name = "ai-proxy"
main = "functions/ai-proxy/index.ts"
compatibility_date = "2024-03-20"

[[services]]
binding = "CREDIT_SERVICE"
service = "credit-service"

[[kv_namespaces]]
binding = "BUDGET_KV"
id = "placeholder_for_local_dev_2"

[vars]
SERVICE_SECRET = "local-secret-string"